-- The six tables plus meta. Applied 2026-09-21 as migration 0001_tables.
--
-- `n` is the permanent posting id, carried over unchanged from the
-- artifact: marks are keyed to it, so it must never be reassigned.

create table if not exists public.postings (
  n                    integer primary key,
  title                text not null,
  title_original       text,                -- the German wording, when translated
  company              text not null,
  city                 text,
  location_group       text,                -- berlin | leipzig | de | eu
  location_label       text,
  category             text not null,       -- sim | sys | data | prod | lead | energy | content
  category_label       text,
  target_category      text,                -- one of the ten search categories
  employment           text,                -- EMPLOYEE | CONTRACT | TRAINEE
  starred              boolean default false,
  url                  text not null,
  eligibility_quote_de text,                -- the exact sentence that qualified it
  eligibility_en       text,
  skills               text[],
  salary               text,
  note                 text,
  duplicate_of         integer,             -- mirror of another posting
  direct_employer_link boolean,
  added_on             date,
  -- A dropped posting keeps its row and gains these two, so the list has
  -- a history instead of things silently vanishing.
  removed_on           date,
  removed_why          text,
  sort_order           integer
);

create table if not exists public.journal (
  id           bigint generated by default as identity primary key,
  run_date     date not null,
  started_at   timestamptz,
  finished_at  timestamptz,
  -- in_progress is what makes live progress possible: the agent writes
  -- this row as it goes and the page re-reads it.
  status       text not null default 'in_progress'
               check (status in ('in_progress','done','did_not_finish')),
  checked      integer,
  live         integer,
  transient    integer,
  per_category jsonb,
  evaluated    jsonb,
  widened      jsonb,
  note         text
);

create table if not exists public.journal_changes (
  id         bigint generated by default as identity primary key,
  journal_id bigint references public.journal(id) on delete cascade,
  direction  text not null check (direction in ('in','out')),
  -- the link that makes "added on Thursday, by category" an exact join
  posting_n  integer,
  title      text,
  company    text,
  why        text
);

create table if not exists public.marks (
  item_id    text primary key,   -- 'j<n>' for a posting, 'c<n>' for a company
  stage      text,
  round      integer,            -- interview round
  stage_at   timestamptz,
  removed    boolean default false,
  note       text,
  updated_at timestamptz default now()
);

create table if not exists public.companies (
  id          text primary key,
  tier        text,              -- A | B | C
  name        text,
  city        text,
  description text,
  tags        text[],
  links       jsonb,
  product     text,              -- tier C only
  url         text,              -- tier C only
  sort_order  integer
);

create table if not exists public.job_boards (
  id             integer primary key,
  label          text,
  url            text,
  location_group text,
  sort_order     integer
);

-- Section titles, category and location labels, the filter rule, the
-- maintenance history and the audit trail: everything the page shows but
-- does not compute.
create table if not exists public.meta (
  key   text primary key,
  value jsonb
);

create index if not exists postings_category_idx on public.postings (category);
create index if not exists postings_live_idx     on public.postings (removed_on) where removed_on is null;
create index if not exists journal_date_idx      on public.journal (run_date desc);
create index if not exists changes_journal_idx   on public.journal_changes (journal_id);
